name: maven compile test

on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  schedule:
    - cron: 0 19 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Validate and Compile with Maven
      run: mvn validate compile
